# syntax=docker/dockerfile:1.4

# See: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

FROM ghcr.io/hammertoe/lotus-fvm-localnet-ready as build

USER root

WORKDIR /home/ubuntu/lotus

RUN apt-get install -y systemd systemd-sysv dbus dbus-user-session

RUN make install install-daemon-service install-miner-service
RUN cp ./lotus-seed /usr/local/bin
RUN cp ./lotus-shed /usr/local/bin

# Copy to new image

FROM ubuntu

RUN useradd ubuntu

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

RUN apt install -y mesa-opencl-icd jq curl hwloc 
RUN apt install -y vim less htop

RUN apt upgrade -y

RUN echo 'root:root' | chpasswd
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d

ENTRYPOINT ["/sbin/init"]


ENV PATH="/usr/local/go/bin:${PATH}"

WORKDIR /home/ubuntu

COPY --from=build /usr/local /usr/local
COPY --from=build /home/ubuntu/.genesis-sectors /home/ubuntu/.genesis-sectors
COPY --from=build /home/ubuntu/.lotus-local-net /home/ubuntu/.lotus-local-net
COPY --from=build /home/ubuntu/.lotus-miner-local-net /home/ubuntu/.lotus-miner-local-net
COPY --from=build /var/tmp/filecoin-proof-parameters /var/tmp/filecoin-proof-parameters
COPY --from=build /var/tmp/filecoin-parents /var/tmp/filecoin-proof-parents
COPY --from=build /etc/systemd/system/lotus-daemon.service /etc/systemd/system/lotus-daemon.service
COPY --from=build /etc/systemd/system/lotus-miner.service /etc/systemd/system/lotus-miner.service
COPY --from=build /var/log/lotus /var/log/lotus
COPY --chown=ubuntu:ubuntu patch-config.sh patch-config.sh

RUN chown -R ubuntu. /home/ubuntu
RUN chown -R ubuntu. /var/tmp

RUN systemctl daemon-reload
RUN systemctl start lotus-daemon
RUN systemctl enable lotus-daemon
RUN systemctl start lotus-miner
RUN systemctl enable lotus-miner

USER ubuntu

RUN chmod +x ./patch-config.sh
RUN ./patch-config.sh

ENV LOTUS_PATH="~/.lotus-local-net"
ENV LOTUS_MINER_PATH="~/.lotus-miner-local-net"
ENV LOTUS_SKIP_GENESIS_CHECK=_yes_

EXPOSE 1234
EXPOSE 2345
