FROM ghcr.io/hammertoe/lotus-fvm-localnet-lite:latest
USER root
WORKDIR /home/ubuntu

RUN apt-get install -y supervisor
RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

#ENV PATH="/usr/local/go/bin:${PATH}"
#ENV LOTUS_PATH="~/.lotus-local-net"
#ENV LOTUS_MINER_PATH="~/.lotus-miner-local-net"
#ENV LOTUS_SKIP_GENESIS_CHECK=_yes_

EXPOSE 1234
EXPOSE 2345

USER ubuntu
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
