# syntax=docker/dockerfile:1.4

FROM ghcr.io/hammertoe/lotus-fvm-localnet-lite@sha256:739cb2f57c0b1233426f50b3b87459ede0a73f0dfac0faf9da74144843f5758e

USER root

RUN apt-get update
RUN apt install -y python3

WORKDIR /home/ubuntu

USER ubuntu

