# syntax=docker/dockerfile:1.4

FROM ghcr.io/hammertoe/lotus-fvm-localnet-lite@sha256:9e361ad9459865a5c01459da6f9ab0faf216d5f24ffeba45df5110f8893968ae

USER root

RUN apt-get update
RUN apt install -y python3

WORKDIR /home/ubuntu

USER ubuntu

