# syntax=docker/dockerfile:1.4

FROM ghcr.io/hammertoe/lotus-fvm-localnet-lite@sha256:c1317e19aa252f8aecbfc6e45344da99c7a376c3200f691638467a4bce4a5e80

USER root

RUN apt-get update
RUN apt install -y python3

WORKDIR /home/ubuntu

USER ubuntu

